meta:
  contract_version: "0.4.0"
  esaa_version: "0.4.x"
  canonical: true
  fail_closed: true

roles:
  orchestrator:
    is_single_writer: true
    reserved_actions:
      - run.start
      - run.end
      - task.create
      - hotfix.create
      - issue.resolve
      - output.rejected
      - orchestrator.file.write
      - orchestrator.view.mutate
      - verify.start
      - verify.ok
      - verify.fail

event_store:
  path: ".roadmap/activity.jsonl"
  format: "jsonl"
  append_only: true
  ordering:
    field: "event_seq"
    monotonic: true
    no_gaps: true

read_models:
  roadmap:
    path: ".roadmap/roadmap.json"
    schema: ".roadmap/roadmap.schema.json"
  issues:
    path: ".roadmap/issues.json"
    schema: ".roadmap/issues.schema.json"
  lessons:
    path: ".roadmap/lessons.json"
    schema: ".roadmap/lessons.schema.json"

validation:
  agent_result_schema: ".roadmap/agent_result.schema.json"
  agent_contract: ".roadmap/AGENT_CONTRACT.yaml"
  reject_on:
    - unknown_action
    - schema_violation
    - boundary_violation
    - immutable_done_violation
    - lock_violation
    - invalid_transition

state_machine:
  task_status_enum: ["todo", "in_progress", "review", "done"]
  transitions:
    - from: "todo"
      on_action: "claim"
      to: "in_progress"
    - from: "in_progress"
      on_action: "complete"
      to: "review"
    - from: "review"
      on_action: "review"
      decision: "approve"
      to: "done"
    - from: "review"
      on_action: "review"
      decision: "request_changes"
      to: "in_progress"

immutability:
  done_is_terminal: true
  reject_status_regression_from_done: true
  correction_flow:
    trigger_action: "issue.report"
    orchestrator_action: "hotfix.create"

pipeline:
  deterministic_steps:
    - parse_event_store
    - select_next_eligible_task
    - dispatch_agent
    - validate_agent_output
    - append_events
    - project_views
    - verify_projection

